---
title: "Project1"
output: html_document
author: "Hannah Wang, Gary Yeung, Jackson Irwin, Ryan Moonka"
---

```{}
Goal 1: Understand the data
```

```{r}
#importing data. CAUTION this takes a LONG time

Jan <- read.csv("201601-citibike-tripdata.csv")
Feb <- read.csv("201602-citibike-tripdata.csv")
Mar <- read.csv("201603-citibike-tripdata.csv")
Apr <- read.csv("201604-citibike-tripdata.csv")
May <- read.csv("201605-citibike-tripdata.csv")
Jun <- read.csv("201606-citibike-tripdata.csv")
Jul <- read.csv("201607-citibike-tripdata.csv")
Aug <- read.csv("201608-citibike-tripdata.csv")
Sep <- read.csv("201609-citibike-tripdata.csv")

```

```{r}
library(ggplot2)
library(dplyr)
library(geosphere)
library(gridExtra)
library(lubridate)
library(anytime)
library(ggmap)
#are dates/times in the same format ie January date/time looks different? does this need to be adjusted?


citiBike_Jan_Sep <- as.data.frame(rbind(Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep))
#final result should have 10262649 obs. of 15 variables
#compilation takes about 15 minutes

#adding distance calculation
citiBike_Jan_Sep <- rowwise(mutate(citiBike_Jan_Sep, distance =
                                     distHaversine(matrix(c(start.station.longitude,
                                                            start.station.latitude),ncol=2),
                                                   matrix(c(end.station.longitude,
                                                            end.station.latitude),ncol=2))))
```

```{r}
#Gender Analysis
citiBike_Jan_Sep$gender <- as.factor(citiBike_Jan_Sep$gender)
by_gender <- filter(citiBike_Jan_Sep, gender == 1 | gender == 2)
by_gender <- group_by(by_gender, gender)
gender_summary <- summarise(by_gender,
  count = n(), avg_distance = mean(distance), med_distance = median(distance),
  avg_duration = mean(tripduration), med_duration = median(tripduration))

#distance
gender_dist_plot<-ggplot(data=by_gender, aes(x=gender, y = distance, colour=gender)) +
  geom_jitter(alpha = 0.25) +
  labs(y="Distance, meters", title="Distance vs. Gender") + 
  scale_x_discrete(breaks = c(1, 2), label = c("Male", "Female")) + 
  guides(colour=FALSE)

#duration
gender_dur_plot<-ggplot(data=by_gender, aes(x=gender, y = tripduration, colour=gender)) +
  geom_jitter(alpha = 0.25) +
  labs(y="Duration, seconds", title="Trip Duration vs. Gender") + 
  scale_x_discrete(breaks = c(1, 2), label = c("Male", "Female")) + 
  guides(colour=FALSE)

#median distance
gender_dist_box <- ggplot(data=by_gender, aes(x=gender, y = distance)) +
  geom_boxplot(aes(fill=gender), outlier.alpha=0) + 
  labs(y="Distance, meters", title="Distance vs. Gender") + 
  scale_x_discrete(breaks = c(1, 2), label = c("Male", "Female")) + 
  guides(fill=FALSE)+
  ylim(0,3000)

#median duration
gender_dur_box <- ggplot(data=by_gender, aes(x=gender, y = tripduration)) +
  geom_boxplot(aes(fill=gender), outlier.alpha=0) + 
  labs(y="Duration, seconds", title="Trip Duration vs. Gender") + 
  scale_x_discrete(breaks = c(1, 2), label = c("Male", "Female")) + 
  guides(fill=FALSE)+
  ylim(0,1500)

#arranging graphs in matrix
grid.arrange(gender_dist_plot,gender_dur_plot,gender_dist_box,gender_dur_box,  ncol=2, nrow = 2)

```

```{r}
#Count of rides by day of the week
#Maybe get rid of fill
#Need to reorder dates, probably go Sunday-Saturday week or Monday-Sunday week

dates <- citiBike_Jan_Sep
dates$starttime <- as.Date(dates$starttime, format = "%m/%d/%Y")
dates <- mutate(dates, day=weekdays(starttime))
dates$weekday_end <- ifelse(dates$day %in% c("Saturday", "Sunday"), "weekend", "weekday")
weekday_weekend_plot <- ggplot(data=dates, aes(x=day,fill=weekday_end)) + 
  geom_bar(stat="count") + 
  labs(x="Day", y="Number of Rides", 
       title = "Number of Rides per Day of the Week, January 2015 through September 2015") +
  guides(fill=guide_legend(title="Weekday or Weekend")) + 
  #scale_x_date(date_labels = "%b-%d", date_breaks = "1 day", expand = c(0.00001,0)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
  scale_fill_manual(values=c("goldenrod","skyblue"))
weekday_weekend_plot

```

```{r}
#Time of Day

popularity <- citiBike_Jan_Sep
popularity$starttime <- floor_date(
  anytime(as.factor(as.POSIXct(
      popularity$starttime, format="%m/%d/%Y %H:%M", tz="America/New_York")), tz="America/New_York"),"1 hour")

#hourly categories (0-23)
popularity$hour_group <- unclass(as.POSIXlt(popularity$starttime)$hour)
popularity$hour_group <- as.factor(popularity$hour_group)

pop_group <- group_by(popularity, start.station.name, start.station.longitude, start.station.latitude,
                      hour_group)
popularity_summary <- summarise(pop_group, count=n())

hour_plot <- ggplot(data=popularity, aes(x=hour_group)) + 
  geom_bar() + 
  labs(x="Hour", y="Number of Rides", title = "Number of Rides per Hour, January through September 2015")
hour_plot



```



```{}
Goal 2: Identify patterns in the ride history data
```



```{}
Goal 3: Assymetric Traffic
```



```{}
Goal 4: Impact of Weather

Using daily weather data for the months of January to September 2016, we will attempt to better understand the impact of weather on the CitiBike system. 

First, let's better visualize the weather data to understand what we're working with. There are a variety of recorded measurements in this weather data - precipitation, snow depth, snowfall, temperature max, temperature min, and average wind speed. 
```

```{r}
library(ggplot2)
library(scales)
library(magrittr)
library(dplyr)
weather_data <- read.csv("weather_data.csv")
weather_data$DATE <- as.Date(as.character(weather_data$DATE), "%Y%m%d")

precip_plot <- ggplot(data=weather_data, aes(x=DATE, y=PRCP), na.rm = TRUE) + geom_point() + geom_smooth(span = 0.3) + xlab("Date") + ylab("Precipitation") + ggtitle("Amount of precipitation from January to September 2016") + scale_x_date(breaks = date_breaks("months"), labels = date_format("%b"))
precip_plot

snowD_plot <- ggplot(data=weather_data, aes(x=DATE, y=SNWD), na.rm = TRUE) + geom_point() + geom_smooth(span = 0.3) + xlab("Date") + ylab("Snow Depth") + ggtitle("Snow depth from January to September 2016") + scale_x_date(breaks = date_breaks("months"), labels = date_format("%b"))
snowD_plot

snowF_plot <- ggplot(data=weather_data, aes(x=DATE, y=SNOW), na.rm = TRUE) + geom_point() + geom_smooth(span = 0.1) + xlab("Date") + ylab("Snowfall") + ggtitle("Amount of snowfall from January to September 2016") + scale_x_date(breaks = date_breaks("months"), labels = date_format("%b"))
snowF_plot

temp_plot <- ggplot(data=weather_data, aes(x=DATE)) + geom_smooth(aes(y=TMAX, colour="max temperature"), span = 0.4) + geom_smooth(aes(y=TMIN, colour="min temperature"), span = 0.4) + scale_color_manual("", breaks=c("max temperature","min temperature"), values=c("red","blue"))+ xlab("Date") + ylab("Temperature") + ggtitle("Max Temperature vs. Min Temperature from January to September 2016") + scale_x_date(breaks = date_breaks("months"), labels = date_format("%b"))
temp_plot

wind_plot <- ggplot(data=weather_data, aes(x=DATE, y=AWND), na.rm = TRUE) + geom_point() + geom_smooth(span = 0.1) + xlab("Date") + ylab("Wind Speed") + ggtitle("Average wind speed from January to September 2016") + scale_x_date(breaks = date_breaks("months"), labels = date_format("%b"))
wind_plot

```

```{}
A few initial observations based on this initial analysis: 
1. It may be more useful to combine the min and max temperature data to calculate an average temperature value and use this average in our analysis.
2. Wind speed data appears to have several unexplained outliers. While most data points are small positive numbers, there are some values of -9999. We're making the assumption that these are invalid data points. We will replace these data points with the mean average wind speed.

A re-visualization of wind speed is below:
```

```{r}
weather_data$AWND[weather_data$AWND < 0] = NA
weather_data$AWND[is.na(weather_data$AWND)] = mean(weather_data$AWND, na.rm=TRUE)
wind_plot <- ggplot(data=weather_data, aes(x=DATE, y=AWND), na.rm = TRUE) + geom_point() + geom_smooth(span = 0.1) + xlab("Date") + ylab("Wind Speed") + ggtitle("Average wind speed from January to September 2016") + scale_x_date(breaks = date_breaks("months"), labels = date_format("%b"))
wind_plot
```



